version: '3.7'

services:
  php:
    build: dev-ops/docker/containers/php
    volumes:
    - shopware:/var/www/app:delegated
    depends_on:
    - mysql
    environment:
      TERM: xterm
      DB_USERNAME: app
      DB_PASSWORD: app
      PHP_IDE_CONFIG: serverName=shopware
    networks:
      shopware:
        aliases:
        - php

  nginx:
    build: dev-ops/docker/containers/nginx
    volumes:
    - shopware:/var/www/app:ro,delegated
    environment:
      TERM: xterm
    depends_on:
    - php
    ports:
    - 8080:8080
    networks:
      shopware:
        aliases:
        - docker.shopware.local

  mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      shopware:
        aliases:
        - mysql

  mail:
    image: tophfr/mailcatcher
    ports:
      - 8081:80
    networks:
      shopware:
        aliases:
        - mail

volumes:
  shopware:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/app
  db:

networks:
  shopware:

#  elastic:
#    build: dev-ops/docker/containers/elastic-search
#    volumes:
#    - ./dev-ops/docker/containers/elastic-search/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
#    - ./dev-ops/docker/_volumes/app-es-data:/usr/share/elasticsearch/data:Z
#    ports:
#    - "9200:9200"
#    - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#
#  redis:
#    build: dev-ops/docker/containers/redis
#    volumes:
#    - ./dev-ops/docker/_volumes/app-redisdata:/data:Z
