version: '3.7'

services:
  php:
    build: dev-ops/docker/containers/php
    volumes:
    - .:/var/www/app:rw,cached
    links:
    - mysql
    depends_on:
    - mysql
    environment:
      DB_USERNAME: app
      DB_PASSWORD: app

  nginx:
    build: dev-ops/docker/containers/nginx
    depends_on:
    - php
    links:
    - php
    ports:
    - 80:80
    volumes:
    - .:/var/www/app

  mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: app
      MYSQL_PASSWORD: app

#  elastic:
#    build: dev-ops/docker/containers/elastic-search
#    volumes:
#    - ./dev-ops/docker/containers/elastic-search/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
#    - ./dev-ops/docker/_volumes/app-es-data:/usr/share/elasticsearch/data:Z
#    ports:
#    - "9200:9200"
#    - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#
#  redis:
#    build: dev-ops/docker/containers/redis
#    volumes:
#    - ./dev-ops/docker/_volumes/app-redisdata:/data:Z
