#!/bin/sh

INSTALL_DIR="/var/www/app/shopware/"
INSTALL_FILE="recovery/install/data/install.lock"

firstRun () {
    if grep -q 1 "${INSTALL_DIR}${INSTALL_FILE}"; then
        echo "Shopware already installed" && \
        return
    else
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:cache:clear && \
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:database:setup --steps=drop,create,import,setupShop --host=docker.shopware.local:8080 && \
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:database:setup --steps=importDemodata,setupShop --host=docker.shopware.local:8080 && \
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:snippets:to:db --include-plugins && \
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:theme:initialize && \
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:admin:create --name="Demo user" --email=demo@example.com --username=demo --password=demo --locale=de_DE && \
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:firstrunwizard:disable && \
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:media:migrate && \
        /usr/local/bin/php ${INSTALL_DIR}bin/console sw:thumbnail:generate && \
        echo 1 > "${INSTALL_DIR}${INSTALL_FILE}" && \
        chown -R www-data:www-data ${INSTALL_DIR} && \
        echo "First run wizard completed" && \
        return
    fi
}

/usr/local/bin/wait-for mysql:3306 -t 300 -- echo "MySQL running" && \
firstRun && \
php-fpm